### ISSUE TITLE
Cannot find module 'less-bundle-promise'

### ISSUE THREAD

**Issue by cipchk** [mzohaibqc/antd-theme-generator#7]
最新版本会产生以下错误：

```
Error: Cannot find module 'less-bundle-promise'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/usr/src/app/node_modules/antd-theme-generator/index.js:6:16)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```

> 另：建议提供简单的版本日志。

**Comment by chenshuai2144** [comment]
人工装一下这个包把

**Comment by mzohaibqc** [comment]
@cipchk This is my fault. I'm fixing this

**Comment by cipchk** [comment]
Hi @mzohaibqc  @chenshuai2144 

I hope to reopen issues, and need to track it.

> My [travis-ci](https://travis-ci.org/cipchk/delon/jobs/421044268) tasks mission can't continue.

**Comment by mzohaibqc** [comment]
@cipchk This has been fixed. Use the lates version

**Comment by cipchk** [comment]
@mzohaibqc thanks for the work
